name: Android CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: List files
      run: |
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        ls -la
        
    - name: Make Gradle executable
      run: chmod +x ./gradlew
      
    - name: Show Gradle version
      run: ./gradlew --version
      
    - name: Build Debug APK
      run: ./gradlew :MyXposedModule:assembleDebug --stacktrace
      
    - name: Build Release APK
      run: ./gradlew :MyXposedModule:assembleRelease --stacktrace
      
    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: MyXposedModule/build/outputs/apk/debug/*.apk
        
    - name: Sign APK
      if: startsWith(github.ref, 'refs/tags/')
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: MyXposedModule/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.KEY_ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          MyXposedModule/build/outputs/apk/release/*-signed.apk
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        body: |
          ## 更新内容
          
          ### 新增功能
          - 支持微信数据备份和恢复
          - 支持多种加密方式
          - 支持自定义备份路径
          - 支持压缩备份文件
          
          ### 安装说明
          1. 下载 APK 文件
          2. 在 LSPosed 管理器中安装并启用模块
          3. 勾选微信应用
          4. 重启手机
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
